### ISSUE TITLE
Errors building from source on Manjaro-Linux

### ISSUE THREAD

**Issue by ddescham74** [Aldo796/BDSP-Randomizers#33]
Hi!
When I build on Linux, I get this errors:
`Traceback (most recent call last):`
`  File "/home/dimitri/.pyenv/versions/3.9.0/lib/python3.9/site-packages/cx_Freeze/initscripts/__startup__.py", line 113, in run
    module_init.run(name + "__main__")`
`  File "/home/dimitri/.pyenv/versions/3.9.0/lib/python3.9/site-packages/cx_Freeze/initscripts/Console.py", line 15, in run
    exec(code, module_main.__dict__)`
`  File "main.py", line 6, in <module>`
`  File "/home/dimitri/BDSP-Randomizers/Randomizers/Starters.py", line 11, in <module>
    from Randomizers.Patches.GameOffsets.GameOffsets import GameOffsets`
`  File "/home/dimitri/BDSP-Randomizers/build/exe.linux-x86_64-3.9/lib/Randomizers/Patches/GameOffsets/GameOffsets.py", line 8
    match gameType:`
........................................................`^`
`SyntaxError: invalid syntax`
Any way to fix them?

PS: the ".........." in front of the " ^ " are for spaces so the symbol is where it is showed on my terminal.

**Comment by Ai0796** [comment]
There's a weird bug with building that requires you to drag the "Randomizers" folder into lib, try that.

**Comment by ddescham74** [comment]
If I build with Python 3.9, still the same error is happening after doing that.

If I build with Python 3.10.1, I get this errors after copying the "Randomizers" folder:
`Traceback (most recent call last):`
`  File "/home/dimitri/.pyenv/versions/3.10.1/lib/python3.10/site-packages/cx_Freeze/initscripts/__startup__.py", line 113, in run
    module_init.run(name + "__main__")`
`  File "/home/dimitri/.pyenv/versions/3.10.1/lib/python3.10/site-packages/cx_Freeze/initscripts/Console.py", line 15, in run
    exec(code, module_main.__dict__)`
`  File "main.py", line 6, in <module>`
`  File "/home/dimitri/BDSP-Randomizers/build/exe.linux-x86_64-3.10/lib/Randomizers/Starters.py", line 12, in <module>
    from Randomizers.Patches.Patch import Patch`
`  File "/home/dimitri/BDSP-Randomizers/build/exe.linux-x86_64-3.10/lib/Randomizers/Patches/Patch.py", line 3, in <module>
    class Patch:`
`  File "/home/dimitri/BDSP-Randomizers/build/exe.linux-x86_64-3.10/lib/Randomizers/Patches/Patch.py", line 4, in Patch
    def __init__(self, shift: int = 0, ks: Ks = None):`
`NameError: name 'Ks' is not  #defined`

Build with 3.10.1 without copying the folder:
`Traceback (most recent call last):`
`  File "/home/dimitri/.pyenv/versions/3.10.1/lib/python3.10/site-packages/cx_Freeze/initscripts/__startup__.py", line 113, in run
    module_init.run(name + "__main__")`
`  File "/home/dimitri/.pyenv/versions/3.10.1/lib/python3.10/site-packages/cx_Freeze/initscripts/Console.py", line 15, in run
    exec(code, module_main.__dict__)`
`  File "main.py", line 6, in <module>`
`  File "/home/dimitri/BDSP-Randomizers/Randomizers/Starters.py", line 11, in <module>
    from Randomizers.Patches.GameOffsets.GameOffsets import GameOffsets`
`  File "/home/dimitri/BDSP-Randomizers/Randomizers/Patches/GameOffsets/GameOffsets.py", line 3, in <module>
    from ..GameOffsets.BD import *`
`AttributeError: module 'Randomizers.Patches.GameOffsets.BD' has no attribute 'BDGameOffsets100'`

**Comment by Ai0796** [comment]
most likely then you don't have all the modules installed. Ks should be keystone-engine

**Comment by ddescham74** [comment]
Oh well, if only I knew I needed to install that as I had to go through errors to try and install all the dependencies. I suggest the creation of a "requirements.txt" so people can install everything and not run into this issue.
I now have a working Linux build.
Thanks for the help.

**Comment by Ai0796** [comment]
added one
